version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./PythonBaseImage
    networks:
      - multi_network
    ports:
      - "50:8000"
  react:
    build:
      context: .
      dockerfile: ./ReactNginxImage
    networks:
      - multi_network
    ports:
      - "80:80"
  redis:
    image: redis
    ports:
      - "6379:6379"
networks:
  multi_network:
