version: '3.9'
services:
  django:
    build:
      context: .
      dockerfile: ./PythonBaseImage
    networks:
      - multi_network
    ports:
      - "6000:8000"
  react:
    build:
      context: .
      dockerfile: ./ReactNginxImage
    networks:
      - multi_network
    ports:
      - "80:80"
networks:
  multi_network:
